# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Print the path to the tools directory
        echo "Agent Tools Directory: $(Agent.ToolsDirectory)"

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Override the tools directory with a custom path
        export AGENT_TOOLSDIRECTORY=/path/to/custom/tools

        # Print the overridden path to the tools directory
        echo "Overridden Agent Tools Directory: $AGENT_TOOLSDIRECTORY"
        
        # Additional commands
        echo 'Hello world1'      
  
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        
        echo 'Hello world2'
