# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

steps:
  - task: Bash@3
    displayName: 'Step 1: Print Tools Directory'
    inputs:
      targetType: 'inline'
      script: |
        # Print the path to the tools directory
        echo "Agent.ToolsDirectory: $(Agent.ToolsDirectory)"

        # Create the /opt/mysharepipeline directory
        mkdir -p /mntsag
        # mkdir -p $(Agent.ToolsDirectory)/mysharepipeline

  - task: Bash@3
    displayName: 'Step 2: Override Tools Directory'
    inputs:
      targetType: 'inline'
      script: |
        # Override the tools directory with a custom path
        export AGENT_TOOLSDIRECTORY=/mntsag

        # Print the overridden path to the tools directory
        echo "Overridden Agent Tools Directory AGENT_TOOLSDIRECTORY: $AGENT_TOOLSDIRECTORY"
        echo "Agent Tools Directory Agent.ToolsDirectory: $(Agent.ToolsDirectory)"
        
        # Additional commands
        echo 'Hello world1'      

  - task: Bash@3
    displayName: 'Step 3: Print Tools Directory Again'
    inputs:
      targetType: 'inline'
      script: |
        # Print the path to the tools directory
        echo "Agent Tools Directory1 Agent.ToolsDirectory: $(Agent.ToolsDirectory)"  
        echo "Overridden Agent Tools Directory AGENT_TOOLSDIRECTORY: $AGENT_TOOLSDIRECTORY"  
        ls
        
  
  - task: Bash@3
    displayName: 'Step 4: Navigate to /home/sagarkalankar/_work/_tool and do ls'
    inputs:
      targetType: 'inline'
      script: |
        # Navigate to the specified path
        cd /home/sagarkalankar/_work/_tool

        # List the contents of the directory
        ls
        
  - task: NodeTool@0
    displayName: 'Step 5: Install Node.js'
    inputs:
      versionSpec: '14.x'
      
  - task: Bash@3
    displayName: 'Step 6: Navigate to /home/sagarkalankar/_work/_tool and do ls'
    inputs:
      targetType: 'inline'
      script: |
        # Navigate to the specified path
        cd /home/sagarkalankar/_work/_tool

        # List the contents of the directory
        ls      

  - task: Bash@3
    displayName: 'Step 7: Navigate to /mntsag and do ls'
    inputs:
      targetType: 'inline'
      script: |
        # Navigate to the specified path
        cd /mntsag

        # List the contents of the directory
        ls  
        pwd

  - task: Bash@3
    displayName: 'Step 8: Navigate to /opt/mysharepipeline and do ls'
    inputs:
      targetType: 'inline'
      script: |
        # Navigate to the specified path
        cd /opt/mysharepipeline

        # List the contents of the directory
        ls    

  - task: Bash@3
    displayName: 'Step 9: Navigate to /mntsag and do ls'
    inputs:
      targetType: 'inline'
      script: |
        # Navigate to the specified path
        cd /mntsag

        # List the contents of the directory
        ls            

  - task: Bash@3
    displayName: 'Step 10: Navigate to /home/sagarkalankar/_work/1 and do ls'
    inputs:
      targetType: 'inline'
      script: |
        # Navigate to the specified path
        cd /home/sagarkalankar/_work/1

        # List the contents of the directory
        ls
