# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Print the path to the tools directory
        echo "Agent Tools Directory: $(Agent.ToolsDirectory)"
  
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        
        echo 'Hello world1'
